---
all:
  vars:
    ansible_user: ansible
    ansible_become: true
    ansible_python_interpreter: /usr/bin/python3
  children:
    linux:
      children:
        rhel_family:
          hosts:
            gitlab.example.com:
              ansible_host: 192.168.1.152
            jenkins.example.com:
              ansible_host: 192.168.1.154
            postgresdb.example.com:
              ansible_host: 192.168.1.169
            logstash.example.com:
              ansible_host: 192.168.1.162
            kibana.example.com:
              ansible_host: 192.168.1.161
            vault.example.com:
              ansible_host: 192.168.1.171
            secopstools.example.com:
              ansible_host: 192.168.1.175
    elk:
      children:
        logstash:
          hosts:
            logstash.example.com:
        kibana:
          hosts:
            kibana.example.com:
    vault:
      hosts:
        vault.example.com:
    dns_clients:
      hosts:
        secopstools.example.com:
